### ISSUE TITLE
Async UI resets scroll position after executing a cell

### ISSUE THREAD

**Issue by okennedy** [VizierDB/web-ui#105]
Actual behavior: After (re-)executing a python cell, the page scrolls up, sometimes moving the python cell (and its result) out of the viewable area.
Expected behavior: After (re-)executing a python cell, the python cell stays in the same position relative to the window.

It's possible that the scroll is the result of shrinking the viewable area as the old result is removed.  To mitigate this bug, and because it's useful, it might be a good idea to preserve the old result value of a cell in-situ until the new value is ready.

**Comment by maqzi** [comment]
Adding some preliminary notes here.

This is a Firefox only issue with the way they manage their scroll anchoring. There are a bunch of [related open bugs in their tracker](https://bugzilla.mozilla.org/buglist.cgi?query_format=advanced&component=Layout%3A%20Scrolling%20and%20Overflow&short_desc=anchor&resolution=---&bug_status=NEW&bug_status=ASSIGNED&bug_status=REOPENED&short_desc_type=allwordssubstr&classification=Client%20Software&classification=Developer%20Infrastructure&classification=Components&classification=Server%20Software&classification=Other&product=Core). Any combination of these could be blocking us.

To reproduce on FF:
1. Create a python cell that outputs a lot of text (e.g., for x in range(1, 50): print(...) ).  
2. Create another python cell with more source code than will fit on the screen at once (e.g 50 lines of comment %foo)
3. Rerun cell 1 and scroll to the bottom of the screen

Expected: the cell 1 output should be appended without scroll position changing
Observed: when cell 1 finishes re-executing it will scroll you to the bottom of the cell 1 output.

**Comment by okennedy** [comment]
Fair enough.  Marking this as an upstream bug.
