### ISSUE TITLE
Code editor is confused about indentation in Python cells

### ISSUE THREAD

**Issue by okennedy** [VizierDB/web-ui#107]
Present behavior:
* Adding a newline after a block start (a line ending in ':') indents using four spaces
* Pressing 'tab' indents using one tab character.

Expected behavior: 
Both auto-indentation after a block start and 'tab' should use the same indentation scheme.

**Comment by okennedy** [comment]
Is there a way to change React's code mirror widget to indent using spaces instead of tabs when the tab key is pressed (alternatively, to indent using tabs when adding newlines).

**Comment by mrb24** [comment]
This is fixed.  PR soon.
