### ISSUE TITLE
Support for Raw SQL cells

### ISSUE THREAD

**Issue by okennedy** [VizierDB/web-ui#11]
It would be useful to have support for cells that execute raw SQL `SELECT` statements.  

## Where does output go?
1. Just shows up in the cell output, as normal.  Perhaps trimmed or tabulated if necessary.
2. [Optionally?] Creates an entirely new table (i.e., CREATE TABLE [x] AS SELECT), with a label given on the cell (Mimir has a "Query Namer" feature that could be used to streamline this step).
3. Overwrite one of the tables used in the query?  (probably not a great idea)

## Support for non-SELECT queries?
Maybe eventually?  For now, I just want to have some way to join/merge two tables.

**Comment by mrb24** [comment]
closed by commit: 43478319d4ff7306fb269c46eae5d6d738c54d44
