### ISSUE TITLE
Collapsable Schemas

### ISSUE THREAD

**Issue by okennedy** [VizierDB/web-ui#111]
Current behavior: The output of cells that create tables has one line per column.  e.g.
```
R(
  A int,
  B float,
  ...
)
```
Especially with lenses, `SELECT` and similar cells, this can lead to very verbose notebook outputs.

Desired behavior: The output of cells that create tables should start out collapsed and have a button to expand the view.      e.g.
```
R( ... 10 columns ... )
```
expanded out to the previous view

**Comment by mrb24** [comment]
if there are more than 10 cols, collapse by default.

**Comment by okennedy** [comment]
No longer relevant: SQL cells no longer display schemas on output.
