### ISSUE TITLE
Display SELECT output instead of schema in SQL and SQL-like cells

### ISSUE THREAD

**Issue by okennedy** [VizierDB/web-ui#112]
Current behavior: SQL, CREATE LENS and similar cells all display the TEXT output tab by default.  This cell shows the schema.  

Desired behvaior: In general, someone using a SQL cell is going to want to see the output.  These cells should default to displaying the output rather than the schema.

**Comment by mrb24** [comment]
All SQL cells should output a dataset.  If they are unnamed concat input names then _01 or something.  the default output for sql cells should be first page of results in datasetview rather than the stdout schema output.

**Comment by okennedy** [comment]
Was closed in the push for CIDR
