### ISSUE TITLE
Auto-generated dataset names in LOAD DATA cells may not be valid table names

### ISSUE THREAD

**Issue by okennedy** [VizierDB/web-ui#119]
If the Name field in a LOAD DATA cell is not populated when the submit button is clicked, it is auto-assigned to be the name of the file (by either the web-ui or the async backend).  However, file-names (especially files with extensions) may not be valid database table names.  

Steps to reproduce:
- Create a LOAD DATA cell.
- Drag/select a file with a period in the name (e.g., a file extension)
- Leave the "Dataset Name" field empty
- Click submit

**Comment by mrb24** [comment]
There is just an error now when dataset name is empty.
