### ISSUE TITLE
Red blob in inter-cell spreadsheet view.

### ISSUE THREAD

**Issue by okennedy** [VizierDB/web-ui#120]
The following occurs after loading a dataset in a python cell where the python cell spills over into the gutter.  The notebook is a direct copy of the first cell from https://demo.vizier.app/vizier-dbprojects/2715e8665a4b485ab0bd21660c6811bf into the async frontend.

![Screenshot from 2019-06-20 17-37-27](https://user-images.githubusercontent.com/3641553/59884374-1c3a6300-9386-11e9-8e02-38a09622ebc8.png)

**Comment by mrb24** [comment]
now a gray blob
