### ISSUE TITLE
'message is undefined' when data source is too big

### ISSUE THREAD

**Issue by okennedy** [VizierDB/web-ui#126]
When uploading a data file that exceeds the API size cap, the API emits a 413 error:
```
 [2019-06-25 15:51:34,064] ERROR in __init__: 413 Request Entity Too Large: The data value transmitted exceeds the capacity limit.
```

This in turn triggers a bug in the UI, which doesn't seem to be able to cope with HTTP errors.
```
TypeError: message is undefined
ErrorMessage
src/core/components/Message.js:32

  29 |         icon='warning sign'
  30 |         header={title}
  31 |         onDismiss={onDismiss}
> 32 |         content={message.charAt(0).toUpperCase() + message.slice(1)}
  33 |     />
  34 | );
  35 | 
```

**Comment by okennedy** [comment]
@mrb24 : Should this be fixed in Vizier-API or the UI?  

Do you want to see how painful it would be to modify Flask to always emit errors in JSON rather than by using HTTP error codes (or perhaps in addition to)?

**Comment by mrb24** [comment]
This is fixed. PR coming soon.   I made changes to Flask error handler to emit 413 errors in JSON that will not break the UI.

**Comment by mrb24** [comment]
closed by web-api-async commit: https://github.com/VizierDB/web-api-async/commit/69c27dc103424d9964d43b056721f6d17a66edbe
