### ISSUE TITLE
Missing Key Lens failed with RAException invalid argument

### ISSUE THREAD

**Issue by lordpretzel** [VizierDB/web-ui#147]
Missing Key Lens fails with invalid argument error:

~~~sh
MimirError:('mimir.algebra.RAException: Invalid argument (missing_only(FALSE)) for MissingKeyLens LENS_missing_key539578734',)
~~~

Used this csv file:

~~~
A,B
1,1
1,2
1,3
2,2
2,3
3,3
4,4
4,5
5,5
~~~
and tried to repair using `A` as a key

**Comment by okennedy** [comment]
I bet this is a case sensitivity bug (is it still present in Mimir v2)?

**Comment by okennedy** [comment]
I can now confirm that this is resolved with Mimir v2
