### ISSUE TITLE
History feature not working

### ISSUE THREAD

**Issue by okennedy** [VizierDB/web-ui#157]
On pip vizier-webapi-0.6 with pyenv python 3.7.4.  

**current behavior**: Opening the history window shows only the initial "load dataset" operation.  Subsequent versions are not displayed.

**desired behavior**: All edits are versioned.

**Comment by mrb24** [comment]
The versioning is actually functioning properly internally, but the history page is not refreshing.  If you refresh (with the browser refresh button) the page, it shows the correct history list.  I need to look into this a bit more.
