### ISSUE TITLE
Schema changes force full re-execution through Mimir

### ISSUE THREAD

**Issue by okennedy** [VizierDB/web-ui#16]
It seems like any change in the spreadsheet forces a full re-execution of the latest cell.  On a sufficiently large data set this means that even trivial changes like updating a column header end up running very slowly. 

Some ideas for fixing this:
 - [ ] Intelligent view caching in Mimir.  This might be easier with spark, as long as we retain the data frames associated with each view.
 - [ ] Use LIMIT clause when rendering data in Vizier (i.e., `SELECT * FROM VIEW LIMIT 100`)

**Comment by heikomuller** [comment]
I believe this was caused by the way annotations were managed in the backend (which required a full SELECT * after adding a new cell). This has been changed now.
