### ISSUE TITLE
Python cell dependency re-execution ignores console output

### ISSUE THREAD

**Issue by okennedy** [VizierDB/web-ui#163]
**Observed behavior**
 - Create a python cell and create/save a dataset within it (you may need to add at least one row)
 - Create a second python cell and *print* the cell values from the earlier dataset
 - Update the first python cell

The second python cell will re-execute, but will not display any console output.

**Expected behavior**
 When the second python cell is re-executed, the (new) output should be displayed.

**Comment by okennedy** [comment]
Similar behavior appears for other cell types as well.  For example, re-executing a SQL cell does not show the Dataset.

**Comment by okennedy** [comment]
@mrb24 : it looks like this is fixed?  Can you confirm?

**Comment by mrb24** [comment]
closed by commit: 51e80cdcf8412b8f2856ef0162cd47c26be67951

**Comment by mrb24** [comment]
I believe that there is some scenario that still causes this to happen, but I have been unable to determine what that is.  so if anyone runs into this, please leave a detailed comment here so that we can track it down.
