### ISSUE TITLE
Python error when plot cell is missing title

### ISSUE THREAD

**Issue by okennedy** [VizierDB/web-ui#167]
**Observed Behavior**: When the plot cell lacks a title, a cryptic python error message is printed out

**Expected Behavior**: 
Ok) Print a sane error message (#79)
Better) Auto-generate a title.

**Comment by mrb24** [comment]
Now we auto-generate plot name based on dataset name in the case where it is left blank. closed by web-api-async commit: https://github.com/VizierDB/web-api-async/commit/70ff6f68adc0006c50b718c4e3de7b080ba5774e
