### ISSUE TITLE
Merge Vizual Commands in Web UI

### ISSUE THREAD

**Issue by okennedy** [VizierDB/web-ui#17]
I'm noticing that Vizual commands tend to accumulate, cluttering up the notebook.  It might be helpful to aggregate them into a single "Vizual Script" workflow step.

**Comment by heikomuller** [comment]
Consecutive VizUAL cells can now be grouped. There are two options: (1) COLLAPSE will show all consecutive VizUAL cells in a single container, (2) Hide (which is the default for now) only displays a short text indicating that there are additional cells that are not shown. The notebook now has a dropdown menu which lets you switch between these modes (or just click on respective icons/texts in the notebook).
