### ISSUE TITLE
'Show Caveats' button in spreadsheet view is not clickable

### ISSUE THREAD

**Issue by okennedy** [VizierDB/web-ui#176]
**Observed Behavior**: In the spreadsheet view (note, not the data view below each cell), cells with caveats include the familiar **(?)** icon, but this icon is not clickable.  Clicking on the icon begins an edit cell interaction

**Expected Behavior**: Clicking on the **(?)** button should open the Caveats window.

**Comment by mrb24** [comment]
closed by commit: 92f390cc34c61f87006ab3ba494e269715cdc833
