### ISSUE TITLE
Python cell fails with error irrespective of content

### ISSUE THREAD

**Issue by lordpretzel** [VizierDB/web-ui#196]
No matter what code I put in a python cell it fails with

~~~sh
TypeError:("'NoneType' object is not subscriptable",)
~~~

- Examples: [https://gram.cse.buffalo.edu/projects/4d2d996c/branches/1d440261/head](https://gram.cse.buffalo.edu/projects/4d2d996c/branches/1d440261/head)
- [https://gram.cse.buffalo.edu/projects/4d2d996c/branches/87b1072b/workflows/00000004](https://gram.cse.buffalo.edu/projects/4d2d996c/branches/87b1072b/workflows/00000004)

**Comment by mrb24** [comment]
closed by web-api-async commit: https://github.com/VizierDB/web-api-async/commit/27491901244c3da39b0624d0a886f90afd12ec5e
