### ISSUE TITLE
No way to delete a value

### ISSUE THREAD

**Issue by okennedy** [VizierDB/web-ui#21]
Deleting the contents of a cell overwrites the cell with '' rather than NULL.

**Comment by heikomuller** [comment]
It would be interesting to know how many users outside the database community are aware of the difference between an empty cell that contains an empty string or a NULL value. It's also not easy to distinguish at input.

Anyway, if you use Ctrl+Del in a spreadsheet cell it will set the cell to NULL. NULL cells are shaded in light grey in the spreadsheet.

**Comment by okennedy** [comment]
That's... actually my point.  

NULL and '' are functionally the same to most spreadsheet users.  However, for us, there are serious differences between how the values behave: '' coerces the type of the column to string, is ignored by the missing value lens, and more.  

@mrb24  Perhaps this problem deserves a little more attention Mimir-side.  Some ideas:

1. Allowing '' to count as a 'vote' for numeric values in the type inference lens (or at least not counting it as a vote for string values)
2. Not allowing '' to coerce the type of a column in Vizier.
3. Modifying the missing value lens to treat '' as a null/missing value.

@lordpretzel, it would be good to get your input too.
