### ISSUE TITLE
"expected int for 'position'" when moving column or row (More broadly, fix move column/row UX)

### ISSUE THREAD

**Issue by okennedy** [VizierDB/web-ui#210]
**Current behavior**: Selecting "Move Column" in a spreadsheet header brings up a dialogue box to select a position.  After entering a number, an error occurs and the spreadsheet is not updated.

**Expected behavior**: The column should move to the indicated position

**Desired behavior**: Users should be able to drag columns to reorder them.

The same issue happens with the "Move Row" operation in spreadsheet row headers.

----- 
## Discussion

The overt problem is that the API attempts to validate the MoveColumn/MoveRow operation and finds a string in the 'position' field instead of a number.  This is a user-entered value, which should be cast to int *before* passing it to the API.  

The deeper problem is that entering a numeric position is a holdover from the development days of Vizier.  We can do better. A typical UI for this task would be to provide handles that can drag the column/row to its new position, but even selecting a new position from a pop-up menu would be friendlier.

**Comment by mrb24** [comment]
make it drag and drop.
