### ISSUE TITLE
Download: Dataset is too big

### ISSUE THREAD

**Issue by okennedy** [VizierDB/web-ui#226]
Dataset downloads are currently implemented through the Query API.  This is a problem because they can get very very very large, which is not something that we want to deal with when calling collect() (as the Query API is wont to do).  We still want to be able to download them though.

In short, this means we want some sort of data streaming API... not collect(), but a way to stream data out of spark and through the network (or, worst case, we materialize the table on disk on-demand and send that to the user).  

Tagging @mrb24 for discussion.

**Comment by mrb24** [comment]
For datasets larger than X we disable download and suggest export dataset.

**Comment by okennedy** [comment]
Updating tags, since we're (hopefully temporarily) plastering this over with UI.
