### ISSUE TITLE
Got a character encoding issue when try to load a .xlsx file locally

### ISSUE THREAD

**Issue by ChrisH2019** [VizierDB/web-ui#233]
Got a character encoding issue when try to load a .xlsx file locally
![Screenshot from 2020-07-01 18-05-28](https://user-images.githubusercontent.com/51105428/86300106-860b6080-bbc7-11ea-9c1d-8d2f797410da.png)

**Comment by okennedy** [comment]
Can't reproduce.  Was able to load the same file without difficulty.

I do recall @mrb24 futzing with the excel plugin a little while ago.  That may have resolved the issue.  Either way, this seems to be working.
