### ISSUE TITLE
Streamline the ramp-up process

### ISSUE THREAD

**Issue by okennedy** [VizierDB/web-ui#234]
**Problem**: New users may be confused when first sitting down to a blank Vizier notebook.

**Ideas**: 
1. When the notebook is empty, have the notebook display big arrow pointing at the [+] button with the label "Start by adding a Load Dataset Cell"
2. Add emphasis (larger font size, bold text, etc...) to the Load Dataset cell when adding the first cell to a notebook.

As a side note, we may want to allow the choice of bold text to be dictated by Vizier-API rather than the UI.  This will make it easier to eventually build a mechanism for triggering suggestions.

**Comment by julianafreire** [comment]
This seems overly complicated.  What about either:
- adding a label to the plus sign (e.g., Add cel), or
- make the interface more similar to that of Jupyter

As for guiding users, we can give them a 1-page tutorial (Getting Started with Vizier) or a sample notebook they can start with; or have an option to "Create Project" which takes the user through a fixed set of steps that includes loading a file.

**Comment by okennedy** [comment]
What parts do you feel are complicated?  I agree that 2. might be a little tricky, but even 1. alone would resolve many of the ramp-up issues we've encountered so far.

Regarding tutorials, we have them.  Nobody uses them (nor, imo, should they be required to during the try-out process).

Regarding a create project flow, could you clarify what you're proposing?  The thought here is simply to add a few unobtrusive breadcrumbs that are always present when specific conditions hold (e.g., when the notebook is empty).
