### ISSUE TITLE
Imports do not clone mimir tables

### ISSUE THREAD

**Issue by ChrisH2019** [VizierDB/web-ui#249]
Internal Error [Mimir]: org.apache.spark.sql.catalyst.analysis.UnresolvedException / An error occurred...

in the project hosted in GitLab
https://demo.vizierdb.info/projects/9679e97a/branches/9d2942bd/head

**Comment by okennedy** [comment]
This is a problem with how imported projects are handled.  We need a cleaner export/import API internally.

**Comment by okennedy** [comment]
Updated Import/Export API is now online.
