### ISSUE TITLE
Spreadsheet edits applied to wrong table

### ISSUE THREAD

**Issue by okennedy** [VizierDB/web-ui#258]
Reproduction steps:

1. Load a dataset
2. Update a cell

**Expected behavior**: The update is applied
**Observed behavior**: The update triggers an error

When edits in the spreadsheet are applied, they use the dataset identifier, and not the current dataset names.  

**Temporary Workaround**: The generated cell can be edited to apply the right dataset.

**Comment by maqzi** [comment]
Can't seem to recreate this. Does #261 solve this?

**Comment by okennedy** [comment]
Let me check now that @mrb24 merged it in.

**Comment by okennedy** [comment]
Confirmed @maqzi : #261 solves the issue.
