### ISSUE TITLE
Can't edit cells after paging

### ISSUE THREAD

**Issue by okennedy** [VizierDB/web-ui#260]
I need to get a proper reproduction of this, but it seems to be the case that once I start paging (definitely after at least 2 clicks on the next page button) I am no longer able to edit cells in the spreadsheet view.

**Comment by mrb24** [comment]
closed by commit: 90ead2b046a066cae8aec564f17f8afb30d3821b and commit: a2578775ba2089b1a2bef0cb174d6ca6a1032d3a
