### ISSUE TITLE
Pycell S3 Loading assumes consistent schema across data files

### ISSUE THREAD

**Issue by okennedy** [VizierDB/web-ui#280]
![image](https://user-images.githubusercontent.com/3641553/94489689-ec961f80-01b2-11eb-8e93-db9f35484161.png)

I think what's happening here is that some of the files have different numbers of fields --- a bunch are NULL.

**Comment by mrb24** [comment]
closed by commit: https://github.com/VizierDB/web-api-async/commit/342bcea7db7dacd85539039584222d035c508f2a
