### ISSUE TITLE
Plot stops showing unique x values with 975 data points or more.

### ISSUE THREAD

**Issue by okennedy** [VizierDB/web-ui#32]
Plot steps appear to be misbehaving whenever given 975 data points or more.  Specifically with 974 data points, we get to see the normal graph.
![screen shot 2018-06-30 at 10 44 20 pm](https://user-images.githubusercontent.com/3641553/42130575-26354762-7cb7-11e8-855d-97762160de24.png)

With 975, they all get collapsed into a single point:
![screen shot 2018-06-30 at 10 45 01 pm](https://user-images.githubusercontent.com/3641553/42130577-3efa90ea-7cb7-11e8-858e-040a24665b08.png)

in the 5-700 range there's also a bit of flakiness: the graph seems to pick up some extra margins.  My guess is that there's some floating point coercion issues.  For example, if the inter-point spacing is coerced into an integer number of pixels, and the width of the drawable space is 974 pixels (e.g., 1000 pixels - 26px axis), then we get int(974/975) = 0.

**Comment by mrb24** [comment]
fixed by commit: eddc4e9a25952d405e577900539d3b5c4665e19d
