### ISSUE TITLE
Allow SQL cells to generate one-shot outputs and new tables

### ISSUE THREAD

**Issue by okennedy** [VizierDB/web-ui#50]
We should provide support for SQL cells that
1. Generate one-shot outputs (i.e., visible only in the notebook) --- this should be the default
2. Overwrite the first (or any) table referenced --- this is currently the default
3. Create an entirely new table

**Comment by mrb24** [comment]
closed with commit: 43478319d4ff7306fb269c46eae5d6d738c54d44
