### ISSUE TITLE
Vizier is slow

### ISSUE THREAD

**Issue by okennedy** [VizierDB/web-ui#53]
Changing the name of one column in a dataset with 42 rows takes 3+ seconds.

**Comment by mrb24** [comment]
notable improvements here:
do not run full query:
    commit: https://github.com/VizierDB/web-api/commit/7e1463998358718de918b9c39df2164e2b913ef2
    commit: https://github.com/VizierDB/web-api/commit/0dbe637326e34cc2c64a03c5d35a492b7a202438
    commit: https://github.com/VizierDB/web-api/commit/28dc460db25f6dd26a607a837432396a04675878
improve state serialization performance: 
    commit: https://github.com/VizierDB/web-api/commit/b7e36f50cfeebedf063f75cdf30c14622420e2fc
avoid serializing and copying full datasets:
    commit: https://github.com/VizierDB/web-api/commit/8d9a1d7034124f9410004dc63d08bc401ca5949a
    commit: https://github.com/VizierDB/web-api/commit/28dc460db25f6dd26a607a837432396a04675878
    commit: https://github.com/UBOdin/mimir/commit/721d54d2edb50260449db850510096ef6d3632a9
some mimir performance improvements:
    commit: https://github.com/UBOdin/mimir/commit/d9a9ef37f693dc08c4956c4ca3aa3ce1ef71a2b2
    commit: https://github.com/UBOdin/mimir/commit/f44fb4a4cac3d32fe9a2240945e13a1cda7a1a83

**Comment by mrb24** [comment]
vizier is faster now.
