### ISSUE TITLE
Automatically optimize sequences of Vizual operations.

### ISSUE THREAD

**Issue by okennedy** [VizierDB/web-ui#66]
Automatically:
 - Re-order operations as appropriate (push computations down)
 - Delete overwritten operations (e.g., two edits to the same cell, or edits to a deleted column).

This information is still preserved in the edit history, so it's not going away entirely (it's still accessible through time machine) but makes it easier to view the Vizual script, and has performance implications.

**Comment by okennedy** [comment]
More generally, what we should do is have a single Vizual script cell, with multiple commands allowed.

**Comment by mrb24** [comment]
dup of #117
