### ISSUE TITLE
Standardize Python / SQL cells' editing and display modes

### ISSUE THREAD

**Issue by okennedy** [VizierDB/web-ui#70]
Right now, the Python (and SQL) cells present the code very differently depending on whether the code is being edited or displayed.  The editing state (1) uses syntax highlighting, and (2) shows only part of the code, while the display state is reversed.

Furthermore, when the code is executed, the switch from editing to display state loses the editor's context (e.g., cursor position).  This is very frustrating when I'm rapidly iterating through revisions of a piece of code, for example when fixing bugs or trying out different visualizations.  

In summary, the request is this (for both Python and SQL cells):
- [x] The size of the editor box should scale to the size of the code.  In other words, the editor should never need to be scrolled 
- [x] The editor box should be retained when the code is run, rather than replacing it with static text.
- [x] The cursor should remain in position.
- [x] Some new visual highlighting might be useful to indicate that a cell has been edited but not re-run.
- [x] Not directly related, but while the editors are being modified, a key combination to run the cell currently being edited would be useful.

**Comment by mrb24** [comment]
closed by commit d975dc7b0d5035344740dc9716948fb576349b11 in UBDev branch
