### ISSUE TITLE
SQL Cells Duplicate Group-By Columns in Console, but not Table output mode

### ISSUE THREAD

**Issue by okennedy** [VizierDB/web-ui#78]
Group by queries such as
```
SELECT LEADING_CAUSE, COUNT(*) FROM Causes GROUP BY LEADING_CAUSE
```
produce inconsistent output.  When dumping to the console, `LEADING_CAUSE` is output twice: Once because it's specified in the SELECT targets, and once because it's a group-by column.  However, when dumping to a table, it's only output once, because it's in the SELECT targets.

**Comment by mrb24** [comment]
superseded by #112
